# Deployment of a container into a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 2
  # select the template
  selector:
    matchLabels:
      app: auth
  # define the pod and the container we want to use
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: rawanad/handiwork-auth:7479b68dc2b744c72a23c74a2d12bb672f86e054
          resources: {}

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10

          # Environment variables
          env:
            # custom name (can be anything)
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  # group name
                  name: auth-db-connection-secret
                  # key name
                  key: auth-db-connection
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      # Cluster IP port
      port: 80
      targetPort: 80
