apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-db-connection-secret
  namespace: handiwork
  creationTimestamp:
spec:
  encryptedData:
    auth-db-connection: AgC2G/7LGRZNoFerUArxFtnfGTVHBne2b70aQlo6Fk8PGvjxmVNqFQr/9uHkKocHghd45w0LNpH0Ak6ohdhY/qPpIsyYRU/pLdS3E8LAzJfkT0jJxHvZ1F9ol9qxN8nhTBAtQ/Lvp7a43KbfIXXbR2O5LrRoWihYe+mHdMDfHc/rpH+jkxRejcTP+GZ/N2Y00JHycjP4JRuHQ5lVzuf/zNZjKCBsyRFCDD3QE2dNOtb3DJmwJWnueahhzOXm/Srkxzyxx/rBCAPjr2upIOu56GPNZyb9e4qpVCX2+uh+fcWMTmNUcgE9zxbP57zIMpI+MSTHy9qUZ2c0AlzFYwg/socdMsyOVNtkXD8qY1pv8iqNS+yHwRZDo+WVm+euXsMKGSGuPFKGCqiXGHtA2qVAPIkV8T92oKkIg2eCuQWTZMsNugp2sCnsIhJ6ns/P4teYNXEJnAtg6Gyli3EzKywbvKbXLI6IbuYu3WsfUm76vMGGrvQRxzT1Fpt4S4V0f/kVNnSyfnQMZjmadT+vo7hRx70XXrHtIiv26dRXUC41KTpKx9Vje6V4AgpBMrrW1Qrb3BlQ12XtmF8+sf9On2YLildLklW2Hky4OMGg1AnO4JGtU26jR3SF6FRxrSht8lXLqUxe2hJ8gj8JuCkHk7KCwIWz3u8gb0A2g0CYke/OhnclM9yEVR49ID3Bk804VJWr4+k4PedQA05j/aVrdjGYVJ9cTCDSUgBLIvHF2faWY/z5B9R68LTGSFd69pCQCg==
