# Deployment of a container into a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: handiwork
spec:
  replicas: 1
  # select the template
  selector:
    matchLabels:
      app: auth
  # define the pod and the container we want to use
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: rawanad/handiwork-auth:32480bc9ba6ac74b0492a43c5a7ba7e8d841d267
          resources: {}

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10

          # Environment variables
          env:
            # custom name (can be anything)
            - name: AUTH_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  # group name
                  name: auth-db-connection-secret
                  # key name
                  key: auth-db-connection
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
  namespace: handiwork
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      # Cluster IP port
      port: 80
      targetPort: 80
