apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: rawanad/handiwork-client:02aa9a2769b9faef7ab18f9851740392d8a6aada
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # the port that the container is running on in the cluster
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: client-clusterip-srv
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 80 # port that the service is running on in the cluster
      targetPort: 80 # port exposed by the service
