apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: handiwork
  creationTimestamp:
spec:
  encryptedData:
    jwt-secret: AgACEVqCm1JjZbhsFPmNxc1UHwfcbYbAmPaZadZIpgSJ6V6BHFj/Z6bPIbLMRNJKqI567CMh6Jj2ghuS7kt7iKjDbVz6AuDArlSlFzen7bh7NFU78TpRuvmAx/Q2z28nlnH0e5aZGg9oMRCWCH89oUvSTrXE/tAjqNCCUskUplopM4y7+4tAyK79krpZdCxyerucx3e/duI43EQZaC4lQ8Jl7NwVFgk64aO5dW1oZEBpiUcvCRw4+2G1phqXhzgTTsOzAHcSGdp1uNDcnDwunpCwarx/oS5rAJ4uo7lIggiy4EfsY2JWTJm12iU2q+MIXA52c4hSYeU65qIy3KOOQvyhdSTPzQjKDp/euS7o+Zou7FuqqP6JhkpjbaUK0KTeOIzq/Lfs4vPRr3l3QYFSiJx4N10y80LUeKW15eK52+7XjkJN/keJmkmPDnJz/dTqiX1wjJmmFYiVXWb508r87nvbX1yrkxNCDt8YVDNizUXwB72Giy0gl00YXHXeeU4OrUKsUditbM81w2n9w1xK7ENrSwA/EG0UpA6heIkinS6xyKQC9d/RfdDU+ZZtDaXI0xzEPw7nBc5cbj0yp0VjnEz+QgSPIc5LJ7trvg2bmlN0vwlNjKAQ2bm4L80tkI/5r/tjqDfj22rggm61+R7VYz6sRzkwwFN7yK9TmhNuBtK53hDawx5vLMh+hb7uvBfejpaX3QDCYf6HmWOkLYBeI4kS2R9qx0McOa0x+gF2MVlE3Q0rsgHq1J4W1C6LxQ==
