apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  #namespace: default
  namespace: argocd
  creationTim/estamp:
spec:
  encryptedData:
    jwt: AgA112O6qGalNdACL1+sXIbUd27AD/znMfUke8Eb39b1pJj3cghgM+LbGcvXfgTrlR1FvyNO3z1evsF64vIc7BHjcemsFsO+UECiIo+jgnaM5Nm0QWdYkCArzlvk7Y02DcYFqW/UOQmVzczZKx0C/ZHgtyloTd/HuhZJFc79kyzlb+bPmag2YLhCm2K2j0wuq0oIukhI03BT9ugnDxfc41wUogiyDEGUh19MZF85qEYKADaNJJDfmqa8C7E8Owl8pA6lS4pgsGBiq5of62AAEhtGoUPdSg7AEOvjtjKbk2f5CE1yALIwRXr/siTTDC4jU9pUfVfaHA1dzqhs10d7/gpDErz4qrz8ddwH1R/idi/PEaaQHygnyKz3pZJj21RDBE92VywijRDUQaSiyCtzjZmnhO1SOiELmQLgN7qdM2sEVV1VhSheZp3rLmVokuThHpxb5lvb3hWlkQ3YaPp2It/yHMrQGLY5WZDrskGj80DVicuX3BbSQews9adlVRuB0eCylgObD6mponMK/T3gLtFssSlsLazBZ8XFHcHc6wdKj7KACd3gxpUnCQ2As1LcR92sCwocVZ7DohBSpBVik8l7edqM3JFMZI8mQ4cxYAHxZzBwKJnZivLKNxnBvNQain5dmttzAVRij+tNCRcnyPjwDilmOTC7YwNo5ZQ00TpzkjCmkRTd4yZQTzLGiGhWTNl4AijS6nKVxF6btuNpmpjMh4lgyP1bbIvvZP1cMsUrdA==
