apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: services-db-connection-secret
  namespace: handiwork
spec:
  encryptedData:
    services-db-connection: AgASr+VoPxhfe4XMcgEXN1pNI+H87JSLZitdpodIvNAtICf9gBYQvyAEtGG+/F+PgfWczal8TXsZNZwN7+mU03sy6VyM4WRE4OEhohHB0R0evDqCdho/E6EdYoWZVhqMtZXKzn0Lan+fnHaWoVOm8Lta9tg1IkLcH4ci3z0Dnx/VfSxaskGtHeFzOGw/lWjuOeKCfzPhAXJWZJumzdjrFT+ph5P/SZ+wGC4pGu6IDwPG4i9Kwkm2Km8qo6Ec39pTUQxdAf2O2tX8vFO1Fwd+R/6MF1o/8MnoyhEz+XKBub8Z0mmpHE2ird2gtQ2m4CiBzDOtuUEQcAGhSHJCr9zt0PEGef+qvumkVnN9f3zta01cB5Xm+NASZxX+kKuctq7/UnKUnGBKk6ShpLkBka7MKciMkVaAIU1W1QsbEeOu69XT2kC35YcbwHwAGJlloenOf55IYA5gdIA5REoAxwg3zvB5vMtXO3dv24nu4qshkIx2MKXFMPFQ/lMc7ry+9K5m4xNEEypcrjCqIr53U6pcpM+ZE4XZbP4xNpIReZFTIY85janPMojUlGx6eIPfsLn9oIp9uw+sPyD9eSl0/x59jwqFpS4JANptDtp/H866YAtrE/1dv6Ctm02evxXnc0JrQvFkDrukmQ0b6cMVKhKbGPc1gkoWSVM+vTaDAYr+ZsJaWfmZReyJbrMwD+1XznJtdCoIWKMHCusFg54lGS3SUwrYvsqSzrEjMrqMAa4JYZaolLMzrqGp1FoLd2j8uLedy1YP/mEjcXzrB+rodCjQwjU46vd7izNG3tuqVOqexCsKv5pF96DuHdrnbLzlrPAPUKRHtlfzW8UZs6GgsUcJRR4edEmq0Ftba88sr6+g5C4HiWhZ5W+gNtaa/9Fcx5NdlvXITK9HeGu2lUDdOXGXhbSxC7N/L/13GVi0DLUZphGSPuugDJGci1UBG4NdIQ93KrBWLcIW+4n3zUKr+/3tn3UmNy/V5dclRnItRPTOg7koO+NkSYcFKnRnn/JHgwpjQvHkZA==

