# Deployment of a container into a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-depl
  namespace: handiwork
spec:
  replicas: 1
  # select the template
  selector:
    matchLabels:
      app: services
  # define the pod and the container we want to use
  template:
    metadata:
      labels:
        app: services
    spec:
      containers:
        - name: services
          image: rawanad/handiwork-services:a944861c89aadbd985034c9e2d53d167abb7224e
          ports:
            - containerPort: 80
          resources: {}

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10

          # Environment variables
          env:
            # custom name (can be anything)
            - name: SERVICES_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  # group name
                  name: services-db-connection-secret
                  # key name
                  key: services-db-connection
            - name: JWT
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt
            - name: RABBIT_MQ
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq
            # Cloudinary
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret
                  key: api-secret

---
apiVersion: v1
kind: Service
metadata:
  name: services-clusterip-srv
  namespace: handiwork
spec:
  type: ClusterIP
  selector:
    app: services
  ports:
    - name: services
      protocol: TCP
      # Cluster IP port
      # port used by other objects
      port: 80
      targetPort: 80
