# Deployment of a container into a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 2
  # select the template
  selector:
    matchLabels:
      app: users
  # define the pod and the container we want to use
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: rawanad/handiwork-users:13e0876133a6de2049e66aa44005f908842d5bbe
          resources: {}

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 10

          startupProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: users-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      # Cluster IP port
      port: 80
      targetPort: 80
