name: K8S Files Validation

on:
  push:
    branches:
      - master
    # run if K8S directory changed
    paths:
      - "K8S"

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@v1.0.0
        with:
          path: "K8S/*.yaml"
          cliArguments: "--only-k8s-files --ignore-missing-schemas"
