name: Docker Build and Push

on:
  push:
    branches:
      - master
    # build and push the images only if one of the microservices or K8S folder changed
    paths:
      - "Auth"
      - "Client"
      - "Services"
      - "Users"
      - "K8S"

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
  DH_USERNAME: ${{ secrets.DH_USERNAME }}
  DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_SHA: ${{ env.GITHUB_SHA }}

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@v1.0.0
        with:
          path: "K8S/*.yaml"
          cliArguments: "--only-k8s-files --ignore-missing-schemas"

  build:
    runs-on: ubuntu-latest

    # run only if k8sPolicyCheck job was a success
    needs: k8sPolicyCheck

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        # You may pin to the exact commit or the version.
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: ${{ secrets.DH_URL }}
          # Username used to log against the Docker registry
          username: ${{ env.DH_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ env.DH_PASSWORD }}
          # Log out from the Docker registry at the end of a job
          logout: true

      - name: Docker build and push
        run: |
          docker build -t ${{ env.DH_USERNAME }}/handiwork-users:latest -t ${{ env.DH_USERNAME }}/handiwork-users:${{ env.GITHUB_SHA }} -f Users/Dockerfile ./Users
          docker push ${{ env.DH_USERNAME }}/handiwork-users:${{ env.GITHUB_SHA }}
          docker push ${{ env.DH_USERNAME }}/handiwork-users:latest

          docker build -t ${{ env.DH_USERNAME }}/handiwork-services:latest -t ${{ env.DH_USERNAME }}/handiwork-services:${{ env.GITHUB_SHA }} -f Services/Dockerfile ./Services
          docker push ${{ env.DH_USERNAME }}/handiwork-services:${{ env.GITHUB_SHA }}
          docker push ${{ env.DH_USERNAME }}/handiwork-services:latest

          docker build -t ${{ env.DH_USERNAME }}/handiwork-auth:latest -t ${{ env.DH_USERNAME }}/handiwork-auth:${{ env.GITHUB_SHA }} -f Auth/Dockerfile ./Auth
          docker push ${{ env.DH_USERNAME }}/handiwork-auth:${{ env.GITHUB_SHA }}
          docker push ${{ env.DH_USERNAME }}/handiwork-auth:latest

          docker build -t ${{ env.DH_USERNAME }}/handiwork-client:latest -t ${{ env.DH_USERNAME }}/handiwork-client:${{ env.GITHUB_SHA }} -f Client/Dockerfile ./Client
          docker push ${{ env.DH_USERNAME }}/handiwork-client:${{ env.GITHUB_SHA }}
          docker push ${{ env.DH_USERNAME }}/handiwork-client:latest

      - name: Update Auth yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: auth
          # Path to the yaml file
          filepath: K8S/auth-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ env.GITHUB_SHA }}

      - name: Update Users yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: users
          # Path to the yaml file
          filepath: K8S/users-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ env.GITHUB_SHA }}

      - name: Update Services yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: services
          # Path to the yaml file
          filepath: K8S/services-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ env.GITHUB_SHA }}

      - name: Update Client yaml file in place
        # You may pin to the exact commit or the version.
        uses: loveholidays/gitops-action-yaml-updater@v1.0.0
        with:
          # TYPE of the new value to be updated
          mode: IMAGE_TAG
          # Name of the container
          container-name: client
          # Path to the yaml file
          filepath: K8S/client-depl.yaml
          # Tag value for the new image
          new-image-tag: ${{ env.GITHUB_SHA }}

      - name: Add & Commit
        # You may pin to the exact commit or the version.
        uses: EndBug/add-and-commit@v9.0.0
        with:
          # Arguments for the git add command
          add: "*"
          # The message for the commit
          message: Update docker image version
          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (more info in the README)
          push: true
          # The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: GitHub Push
        # You may pin to the exact commit or the version.
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ env.GITHUB_TOKEN }}
          # Destination branch to push changes
          branch: master
          # Determines if force push is used
          force: false
