name: Validate Kubernetes & Docker Build

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "**"

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
  # Validate Kubernetes files
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@v1.0.0
        with:
          path: "K8S/*.yaml"
          cliArguments: "--only-k8s-files --ignore-missing-schemas"

  # Build Docker images and tag them
  build:
    runs-on: ubuntu-latest

    # run only if k8sPolicyCheck job was a success
    #needs: k8sPolicyCheck

    steps:
      - uses: actions/checkout@v3

      - name: Build Users Docker image
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-users-pr:${{ github.sha }} -f Users/Dockerfile ./Users

      - name: Build Services Docker image
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-services-pr:${{ github.sha }} -f Services/Dockerfile ./Services

      - name: Build Auth Docker image
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-auth-pr:${{ github.sha }} -f Auth/Dockerfile ./Auth

      - name: Build Client Docker image
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-client-pr:${{ github.sha }} -f Client/Dockerfile ./Client
