name: Docker Build and Push, Kubernetes start

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: ${{ secrets.DH_URL }}
          # Username used to log against the Docker registry
          username: ${{ secrets.DH_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DH_PASSWORD }}
          # Log out from the Docker registry at the end of a job
          logout: true

      - name: Docker build and push, kubectl apply
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-users:${{ github.sha }} -f Users/Dockerfile ./Users
          docker push ${{ secrets.DH_USERNAME }}/handiwork-users:${{ github.sha }}

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-services:${{ github.sha }} -f Services/Dockerfile ./Services
          docker push ${{ secrets.DH_USERNAME }}/handiwork-services:${{ github.sha }}

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-auth:${{ github.sha }} -f Auth/Dockerfile ./Auth
          docker push ${{ secrets.DH_USERNAME }}/handiwork-auth:${{ github.sha }}

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-client:${{ github.sha }} -f Client/Dockerfile ./Client
          docker push ${{ secrets.DH_USERNAME }}/handiwork-client:${{ github.sha }}
                    
      - name: Kubernetes 
        # You may pin to the exact commit or the version.
        # uses: steebchen/kubectl@bd911c0b014904226d4cbd571ec0f7b679c5bb7c
        uses: steebchen/kubectl@v2.0.0
        with:
          # kubectl version, e.g. `v1.21.0`, defaults to latest
          version: latest
          # kube config data
          #config: ${{ secrets.KUBE_CONFIG }}
          # kubectl command to run, without the kubectl, e.g. `get pods`
          command: apply -f K8S/*
