name: Docker Build and Push, Kubernetes start

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        uses: docker/login-action@v2.0.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          # registry: ${{ secrets.DH_URL }}
          # Username used to log against the Docker registry
          username: ${{ secrets.DH_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DH_PASSWORD }}
          # Log out from the Docker registry at the end of a job
          logout: true

      - name: Docker build and push, kubectl apply
        run: |
          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-users:latest -t ${{ secrets.DH_USERNAME }}/handiwork-users:${{ github.sha }} -f Users/Dockerfile ./Users
          docker push ${{ secrets.DH_USERNAME }}/handiwork-users:${{ github.sha }}
          docker push ${{ secrets.DH_USERNAME }}/handiwork-users:latest

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-services:latest -t ${{ secrets.DH_USERNAME }}/handiwork-services:${{ github.sha }} -f Services/Dockerfile ./Services
          docker push ${{ secrets.DH_USERNAME }}/handiwork-services:${{ github.sha }}
          docker push ${{ secrets.DH_USERNAME }}/handiwork-services:latest

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-auth:latest -t ${{ secrets.DH_USERNAME }}/handiwork-auth:${{ github.sha }} -f Auth/Dockerfile ./Auth
          docker push ${{ secrets.DH_USERNAME }}/handiwork-auth:${{ github.sha }}
          docker push ${{ secrets.DH_USERNAME }}/handiwork-auth:latest

          docker build -t ${{ secrets.DH_USERNAME }}/handiwork-client:latest -t ${{ secrets.DH_USERNAME }}/handiwork-client:${{ github.sha }} -f Client/Dockerfile ./Client
          docker push ${{ secrets.DH_USERNAME }}/handiwork-client:${{ github.sha }}
          docker push ${{ secrets.DH_USERNAME }}/handiwork-client:latest

          kubectl apply -f K8S/*
