name: Snyk Docker Image Scan

on: 
  - push
  - workflow_dispatch

env:
  DH_USERNAME: ${{ secrets.DH_USERNAME }}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.DH_USERNAME }}/handiwork-users:latest
        args: --severity-threshold=high
